format = """[](#3c3c3c)\
$os\
$username\
[](bg:#3c3c3c fg:#50a3c1)\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
[](bg:#3c3c3c fg:#50a3c1)\
$time\
[](fg:#3c3c3c)\
\n$character"""

add_newline = false

[character]
success_symbol = '[⟶](bold green)'
error_symbol = '[⟶](bold red)'

[username]
show_always = true
style_user = "bg:#3c3c3c"
style_root = "bg:#3c3c3c"
format = '[$user ]($style)'
aliases = { "lambdawolf" = "" }

[os]
style = "bg:#3c3c3c"
disabled = false # Disabled by default

[os.symbols]
Macos = " "

[directory]
style = "bg:#3c3c3c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#3c3c3c fg:#89f497"
format = '[[](bg:#3c3c3c fg:#50a3c1) $symbol $branch ]($style)'

[git_status]
style = "bg:#3c3c3c fg:#89f497"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[gradle]
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1) $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#3c3c3c"
format = '[[](bg:#3c3c3c fg:#50a3c1)  $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3c3c3c"
format = '[ ♥ $time ]($style)'
